ARG ALPINE_IMAGE=alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
FROM ${ALPINE_IMAGE}

RUN apk add --no-cache openrc \
    && sed -i '/^tty[1-6]::respawn:/d' /etc/inittab

CMD ["/sbin/init"]
