// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commonpb/common.proto

package commonpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_72ef68428b411a7d, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// Request - Common fields used in all gRPC requests
type Request struct {
	Async                bool     `protobuf:"varint,1,opt,name=Async,proto3" json:"Async,omitempty"`
	Timeout              int64    `protobuf:"varint,2,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	SessionID            uint32   `protobuf:"varint,9,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_72ef68428b411a7d, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetAsync() bool {
	if m != nil {
		return m.Async
	}
	return false
}

func (m *Request) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Request) GetSessionID() uint32 {
	if m != nil {
		return m.SessionID
	}
	return 0
}

// Response - Common fields used in all gRPC responses. Note that this field
//            only used when the implant needs to return an error to the server.
//            Client<->Server comms should use normal gRPC error handling.
type Response struct {
	Err                  string   `protobuf:"bytes,1,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_72ef68428b411a7d, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

// File - A basic file data type
type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_72ef68428b411a7d, []int{3}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Process - A basic process data type
type Process struct {
	Pid                  int32    `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid,omitempty"`
	Ppid                 int32    `protobuf:"varint,2,opt,name=Ppid,proto3" json:"Ppid,omitempty"`
	Executable           string   `protobuf:"bytes,3,opt,name=Executable,proto3" json:"Executable,omitempty"`
	Owner                string   `protobuf:"bytes,4,opt,name=Owner,proto3" json:"Owner,omitempty"`
	SessionID            int32    `protobuf:"varint,5,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_72ef68428b411a7d, []int{4}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Process) GetPpid() int32 {
	if m != nil {
		return m.Ppid
	}
	return 0
}

func (m *Process) GetExecutable() string {
	if m != nil {
		return m.Executable
	}
	return ""
}

func (m *Process) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Process) GetSessionID() int32 {
	if m != nil {
		return m.SessionID
	}
	return 0
}

// EnvVar - Environment variable K/V
type EnvVar struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnvVar) Reset()         { *m = EnvVar{} }
func (m *EnvVar) String() string { return proto.CompactTextString(m) }
func (*EnvVar) ProtoMessage()    {}
func (*EnvVar) Descriptor() ([]byte, []int) {
	return fileDescriptor_72ef68428b411a7d, []int{5}
}

func (m *EnvVar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnvVar.Unmarshal(m, b)
}
func (m *EnvVar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnvVar.Marshal(b, m, deterministic)
}
func (m *EnvVar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnvVar.Merge(m, src)
}
func (m *EnvVar) XXX_Size() int {
	return xxx_messageInfo_EnvVar.Size(m)
}
func (m *EnvVar) XXX_DiscardUnknown() {
	xxx_messageInfo_EnvVar.DiscardUnknown(m)
}

var xxx_messageInfo_EnvVar proto.InternalMessageInfo

func (m *EnvVar) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *EnvVar) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "commonpb.Empty")
	proto.RegisterType((*Request)(nil), "commonpb.Request")
	proto.RegisterType((*Response)(nil), "commonpb.Response")
	proto.RegisterType((*File)(nil), "commonpb.File")
	proto.RegisterType((*Process)(nil), "commonpb.Process")
	proto.RegisterType((*EnvVar)(nil), "commonpb.EnvVar")
}

func init() {
	proto.RegisterFile("commonpb/common.proto", fileDescriptor_72ef68428b411a7d)
}

var fileDescriptor_72ef68428b411a7d = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x89, 0x6d, 0x9a, 0x66, 0x50, 0x90, 0x45, 0x21, 0x87, 0x22, 0x25, 0xa7, 0x5e, 0x6c,
	0x04, 0x3f, 0x81, 0xd2, 0x08, 0x52, 0xd0, 0xb2, 0x4a, 0x05, 0x6f, 0x49, 0x3a, 0xb5, 0x0b, 0x49,
	0x36, 0xee, 0x9f, 0xda, 0x9c, 0xfd, 0xe2, 0xb2, 0x13, 0x83, 0xf5, 0xf6, 0x7b, 0x6f, 0x99, 0xb7,
	0xf3, 0x18, 0xb8, 0x2c, 0x64, 0x55, 0xc9, 0xba, 0xc9, 0x93, 0x0e, 0xe6, 0x8d, 0x92, 0x46, 0xb2,
	0x71, 0x6f, 0xc7, 0x01, 0xf8, 0x69, 0xd5, 0x98, 0x36, 0x7e, 0x83, 0x80, 0xe3, 0xa7, 0x45, 0x6d,
	0xd8, 0x05, 0xf8, 0x77, 0xba, 0xad, 0x8b, 0xc8, 0x9b, 0x7a, 0xb3, 0x31, 0xef, 0x04, 0x8b, 0x20,
	0x78, 0x15, 0x15, 0x4a, 0x6b, 0xa2, 0x93, 0xa9, 0x37, 0x1b, 0xf0, 0x5e, 0xb2, 0x09, 0x84, 0x2f,
	0xa8, 0xb5, 0x90, 0xf5, 0xe3, 0x22, 0x0a, 0xa7, 0xde, 0xec, 0x8c, 0xff, 0x19, 0xf1, 0x04, 0xc6,
	0x1c, 0x75, 0x23, 0x6b, 0x8d, 0xec, 0x1c, 0x06, 0xa9, 0x52, 0x94, 0x1b, 0x72, 0x87, 0xf1, 0x1c,
	0x86, 0x0f, 0xa2, 0x44, 0xc6, 0x60, 0xf8, 0x94, 0x55, 0xf8, 0xfb, 0x44, 0xec, 0xbc, 0x45, 0x66,
	0x32, 0xfa, 0xee, 0x94, 0x13, 0xc7, 0xdf, 0x1e, 0x04, 0x2b, 0x25, 0x0b, 0xd4, 0xda, 0xa5, 0xad,
	0xc4, 0x86, 0x46, 0x7c, 0xee, 0xd0, 0x4d, 0xac, 0x1a, 0xb1, 0xa1, 0x09, 0x9f, 0x13, 0xb3, 0x2b,
	0x80, 0xf4, 0x80, 0x85, 0x35, 0x59, 0x5e, 0x62, 0x34, 0xa0, 0xfc, 0x23, 0xc7, 0xb5, 0x7d, 0xfe,
	0xaa, 0x51, 0x45, 0x43, 0x7a, 0xea, 0xc4, 0xff, 0x4e, 0x3e, 0xc5, 0x1d, 0x75, 0xba, 0x81, 0x51,
	0x5a, 0xef, 0xd7, 0x99, 0x72, 0x3b, 0x2c, 0xb1, 0xed, 0x1b, 0x2d, 0xb1, 0x75, 0x79, 0xeb, 0xac,
	0xb4, 0x48, 0x4b, 0x84, 0xbc, 0x13, 0xf7, 0xc9, 0xfb, 0xf5, 0x87, 0x30, 0x3b, 0x9b, 0xcf, 0x0b,
	0x59, 0x25, 0xb9, 0xd0, 0x3b, 0xd9, 0x6c, 0xe5, 0x21, 0xd1, 0xa5, 0xd8, 0xa3, 0x4a, 0xe8, 0x2c,
	0xb9, 0xdd, 0x26, 0xfd, 0x61, 0xf2, 0x11, 0x59, 0xb7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x42,
	0x76, 0x6e, 0x85, 0xc2, 0x01, 0x00, 0x00,
}
