package creds

// hashTypes maps protobuf enum identifiers to the exact human-readable
// names reported by the bundled Hashcat v7.1.2-armory.1 modules at commit
// deadd52de22e2753e9caaff6d1b92e5a22a35626.
var hashTypes = map[string]string{
	"MD5":                                   "MD5",
	"MD5_PW_SALT":                           "md5($pass.$salt)",
	"JOOMLA_2_5_18":                         "Joomla < 2.5.18",
	"POSTGRESQL":                            "PostgreSQL",
	"MD5_SALT_PW":                           "md5($salt.$pass)",
	"OSCOMMERCE_XT_COMMERCE":                "osCommerce, xt:Commerce",
	"JUNIPER_NETSCREEN_SSG_SCREENOS":        "Juniper NetScreen/SSG (ScreenOS)",
	"SKYPE":                                 "Skype",
	"SOLARWINDS_SERV_U":                     "SolarWinds Serv-U",
	"MD5_UTF16LE_PASS_SALT":                 "md5(utf16le($pass).$salt)",
	"MD5_SALT_UTF16LE_PASS":                 "md5($salt.utf16le($pass))",
	"HMAC_MD5_KEY_PASS":                     "HMAC-MD5 (key = $pass)",
	"HMAC_MD5_KEY_SALT":                     "HMAC-MD5 (key = $salt)",
	"MD5_UTF16LE":                           "md5(utf16le($pass))",
	"SHA1":                                  "SHA1",
	"NSLDAP_SHA_1_BASE64_NETSCAPE_LDAP_SHA": "nsldap, SHA-1(Base64), Netscape LDAP SHA",
	"SHA1_PASS_SALT":                        "sha1($pass.$salt)",
	"NSLDAPS_SSHA_1_BASE64_NETSCAPE_LDAP_SSHA": "nsldaps, SSHA-1(Base64), Netscape LDAP SSHA",
	"ORACLE_S_TYPE_ORACLE_11":                  "Oracle S: Type (Oracle 11+)",
	"SHA1_SALT_PASS":                           "sha1($salt.$pass)",
	"SMF_SIMPLE_MACHINES_FORUM_V1_1":           "SMF (Simple Machines Forum) > v1.1",
	"MACOS_V10_4_MACOS_V10_5_MACOS_V10_6":      "macOS v10.4, macOS v10.5, macOS v10.6",
	"DJANGO_SHA_1":                             "Django (SHA-1)",
	"ARUBAOS":                                  "ArubaOS",
	"SHA1_UTF16LE_PASS_SALT":                   "sha1(utf16le($pass).$salt)",
	"MSSQL_2000":                               "MSSQL (2000)",
	"MSSQL_2005":                               "MSSQL (2005)",
	"PEOPLESOFT":                               "PeopleSoft",
	"SHA1_SALT_UTF16LE_PASS":                   "sha1($salt.utf16le($pass))",
	"EPISERVER_6_X_NET_4_MODE_141":             "Episerver 6.x < .NET 4",
	"HMAC_SHA1_KEY_PASS":                       "HMAC-SHA1 (key = $pass)",
	"HMAC_SHA1_KEY_SALT":                       "HMAC-SHA1 (key = $salt)",
	"SHA1_UTF16LE":                             "sha1(utf16le($pass))",
	"MYSQL323":                                 "MySQL323",
	"MYSQL4_1_MYSQL5":                          "MySQL4.1/MySQL5",
	"PHPASS":                                   "phpass",
	"MD5CRYPT_MD5_UNIX_CISCO_IOS_1_MD5":        "md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5)",
	"JUNIPER_IVE":                              "Juniper IVE",
	"BLAKE2B_256":                              "BLAKE2b-512",
	"BLAKE2B_512_PW_SALT":                      "BLAKE2b-512($pass.$salt)",
	"BLAKE2B_512_SALT_PW":                      "BLAKE2b-512($salt.$pass)",
	"MD4":                                      "MD4",
	"NTLM":                                     "NTLM",
	"DCC":                                      "Domain Cached Credentials (DCC), MS Cache",
	"SHA2_224":                                 "SHA2-224",
	"SHA224_PASS_SALT":                         "sha224($pass.$salt)",
	"SHA224_SALT_PASS":                         "sha224($salt.$pass)",
	"SHA2_256":                                 "SHA2-256",
	"SHA256_PASS_SALT":                         "sha256($pass.$salt)",
	"SSHA_256_BASE64_LDAP_SSHA256":             "SSHA-256(Base64), LDAP {SSHA256}",
	"SHA256_SALT_PASS":                         "sha256($salt.$pass)",
	"HMAILSERVER":                              "hMailServer",
	"SHA256_UTF16LE_PASS_SALT":                 "sha256(utf16le($pass).$salt)",
	"SHA256_SALT_UTF16LE_PASS":                 "sha256($salt.utf16le($pass))",
	"EPISERVER_6_X_NET_4_MODE_1441":            "Episerver 6.x >= .NET 4",
	"HMAC_SHA256_KEY_PASS":                     "HMAC-SHA256 (key = $pass)",
	"HMAC_SHA256_KEY_SALT":                     "HMAC-SHA256 (key = $salt)",
	"SHA256_UTF16LE":                           "sha256(utf16le($pass))",
	"DESCRYPT_DES_UNIX_TRADITIONAL_DES":        "descrypt, DES (Unix), Traditional DES",
	"APACHE_APR1_MD5_MD5APR1_MD5_APR":          "Apache $apr1$ MD5, md5apr1, MD5 (APR)",
	"SHA2_512":                                 "SHA2-512",
	"SHA512_PASS_SALT":                         "sha512($pass.$salt)",
	"SSHA_512_BASE64_LDAP_SSHA512":             "SSHA-512(Base64), LDAP {SSHA512}",
	"SHA512_SALT_PASS":                         "sha512($salt.$pass)",
	"MACOS_V10_7":                              "macOS v10.7",
	"SHA512_UTF16LE_PASS_SALT":                 "sha512(utf16le($pass).$salt)",
	"MSSQL_2012_2014":                          "MSSQL (2012, 2014)",
	"SHA512_SALT_UTF16LE_PASS":                 "sha512($salt.utf16le($pass))",
	"HMAC_SHA512_KEY_PASS":                     "HMAC-SHA512 (key = $pass)",
	"HMAC_SHA512_KEY_SALT":                     "HMAC-SHA512 (key = $salt)",
	"SHA512_UTF16LE":                           "sha512(utf16le($pass))",
	"SHA512_CRYPT_UNIX":                        "sha512crypt $6$, SHA512 (Unix)",
	"STDOUT":                                   "STDOUT",
	"DCC2":                                     "Domain Cached Credentials 2 (DCC2), MS Cache 2",
	"CISCO_PIX_MD5":                            "Cisco-PIX MD5",
	"CISCO_ASA_MD5":                            "Cisco-ASA MD5",
	"WPA_EAPOL_PBKDF2":                         "WPA-EAPOL-PBKDF2",
	"WPA_EAPOL_PMK":                            "WPA-EAPOL-PMK",
	"MD5_MD5_PASS":                             "md5(md5($pass))",
	"VBULLETIN_V3_8_5_MODE_2611":               "vBulletin < v3.8.5",
	"PHPS":                                     "PHPS",
	"MD5_MD5_PASS_SALT":                        "md5(md5($pass.$salt))",
	"VBULLETIN_V3_8_5_MODE_2711":               "vBulletin >= v3.8.5",
	"MYBB_1_2_IPB2_INVISION_POWER_BOARD":       "MyBB 1.2+, IPB2+ (Invision Power Board)",
	"LM":                                       "LM",
	"ORACLE_H_TYPE_ORACLE_7":                   "Oracle H: Type (Oracle 7+)",
	"BCRYPT_UNIX":                              "bcrypt $2*$, Blowfish (Unix)",
	"MD5_MD5_MD5_PASS":                         "md5(md5(md5($pass)))",
	"MD5_MD5_MD5_PASS_SALT":                    "md5(md5(md5($pass)).$salt)",
	"MD5_SALT_MD5_PW":                          "md5($salt.md5($pass))",
	"MEDIAWIKI_B_TYPE":                         "MediaWiki B type",
	"MD5_SALT1_STRTOUPPER_MD5_SALT2_PASS":      "md5($salt1.strtoupper(md5($salt2.$pass)))",
	"MD5_SALT_PW_SALT":                         "md5($salt.$pass.$salt)",
	"MD5_MD5_PASS_MD5_SALT":                    "md5(md5($pass).md5($salt))",
	"MD5_SALT_MD5_SALT_PASS":                   "md5($salt.md5($salt.$pass))",
	"MD5_SALT_MD5_PASS_SALT_MODE_4110":         "md5($salt.md5($pass.$salt))",
	"MD5_STRTOUPPER_MD5_PASS":                  "md5(strtoupper(md5($pass)))",
	"MD5_SHA1_PASS":                            "md5(sha1($pass))",
	"MD5_SHA1_PASS_SALT_MODE_4410":             "md5(sha1($pass).$salt)",
	"MD5_SHA1_PASS_SALT_MODE_4420":             "md5(sha1($pass.$salt))",
	"MD5_SHA1_SALT_PASS":                       "md5(sha1($salt.$pass))",
	"SHA1_SHA1_PASS":                           "sha1(sha1($pass))",
	"SHA1_SHA1_PASS_SALT":                      "sha1(sha1($pass).$salt)",
	"SHA1_SALT_SHA1_PASS":                      "sha1($salt.sha1($pass))",
	"REDMINE":                                  "Redmine",
	"PUNBB":                                    "PunBB",
	"SHA1_MD5_PASS":                            "sha1(md5($pass))",
	"SHA1_MD5_PASS_SALT_MODE_4710":             "sha1(md5($pass).$salt)",
	"HUAWEI_SHA1_MD5_PASS_SALT":                "Huawei sha1(md5($pass).$salt)",
	"ISCSI_CHAP":                               "iSCSI CHAP authentication, MD5(CHAP)",
	"SHA1_SALT_PASS_SALT":                      "sha1($salt.$pass.$salt)",
	"SHA1_SHA1_SALT_PASS_SALT":                 "sha1(sha1($salt.$pass.$salt))",
	"HALF_MD5":                                 "Half MD5",
	"PASSWORD_SAFE_V3":                         "Password Safe v3",
	"IKE_MD5":                                  "IKE-PSK MD5",
	"IKE_SHA1":                                 "IKE-PSK SHA1",
	"NET_NTLM_V1":                              "NetNTLMv1 / NetNTLMv1+ESS",
	"NET_NTLM_V2":                              "NetNTLMv2",
	"CISCO_IOS_TYPE_4_SHA256":                  "Cisco-IOS type 4 (SHA256)",
	"CISCO_ISE_HASHED_PASSWORD_SHA256":         "Cisco-ISE Hashed Password (SHA256)",
	"SAMSUNG_ANDROID":                          "Samsung Android Password/PIN",
	"RIPEMD_160":                               "RIPEMD-160",
	"HMAC_RIPEMD160_KEY_PASS":                  "HMAC-RIPEMD160 (key = $pass)",
	"HMAC_RIPEMD160_KEY_SALT":                  "HMAC-RIPEMD160 (key = $salt)",
	"WHIRLPOOL":                                "Whirlpool",
	"TRUECRYPT_RIPEMD160_XTS_512_BIT_LEGACY":   "TrueCrypt RIPEMD160 + XTS 512 bit (legacy)",
	"TRUECRYPT_RIPEMD160_XTS_1024_BIT_LEGACY":  "TrueCrypt RIPEMD160 + XTS 1024 bit (legacy)",
	"TRUECRYPT_RIPEMD160_XTS_1536_BIT_LEGACY":  "TrueCrypt RIPEMD160 + XTS 1536 bit (legacy)",
	"TRUECRYPT_SHA512_XTS_512_BIT_LEGACY":      "TrueCrypt SHA512 + XTS 512 bit (legacy)",
	"TRUECRYPT_SHA512_XTS_1024_BIT_LEGACY":     "TrueCrypt SHA512 + XTS 1024 bit (legacy)",
	"TRUECRYPT_SHA512_XTS_1536_BIT_LEGACY":     "TrueCrypt SHA512 + XTS 1536 bit (legacy)",
	"TRUECRYPT_WHIRLPOOL_XTS_512_BIT_LEGACY":   "TrueCrypt Whirlpool + XTS 512 bit (legacy)",
	"TRUECRYPT_WHIRLPOOL_XTS_1024_BIT_LEGACY":  "TrueCrypt Whirlpool + XTS 1024 bit (legacy)",
	"TRUECRYPT_WHIRLPOOL_XTS_1536_BIT_LEGACY":  "TrueCrypt Whirlpool + XTS 1536 bit (legacy)",
	"TRUECRYPT_RIPEMD160_XTS_512_BIT_BOOT_MODE_LEGACY":  "TrueCrypt RIPEMD160 + XTS 512 bit + boot-mode (legacy)",
	"TRUECRYPT_RIPEMD160_XTS_1024_BIT_BOOT_MODE_LEGACY": "TrueCrypt RIPEMD160 + XTS 1024 bit + boot-mode (legacy)",
	"TRUECRYPT_RIPEMD160_XTS_1536_BIT_BOOT_MODE_LEGACY": "TrueCrypt RIPEMD160 + XTS 1536 bit + boot-mode (legacy)",
	"AIX_SMD5":                                             "AIX {smd5}",
	"AIX_SSHA256":                                          "AIX {ssha256}",
	"AIX_SSHA512":                                          "AIX {ssha512}",
	"HASHCAT_1PASSWORD_AGILEKEYCHAIN":                      "1Password, agilekeychain",
	"AIX_SSHA1":                                            "AIX {ssha1}",
	"LASTPASS_LASTPASS_SNIFFED":                            "LastPass + LastPass sniffed",
	"GOST_R_34_11_94":                                      "GOST R 34.11-94",
	"FORTIGATE_FORTIOS":                                    "FortiGate (FortiOS)",
	"MACOS_10_8":                                           "macOS v10.8+ (PBKDF2-SHA512)",
	"GRUB_2":                                               "GRUB 2",
	"IPMI2_PAKP_HMAC_SHA1":                                 "IPMI2 RAKP HMAC-SHA1",
	"IPMI2_RAKP_HMAC_MD5":                                  "IPMI2 RAKP HMAC-MD5",
	"SHA256CRYPT_5_SHA256_UNIX":                            "sha256crypt $5$, SHA256 (Unix)",
	"MYSQL_A_SHA256CRYPT":                                  "MySQL $A$ (sha256crypt)",
	"KERBEROS_23_SA_REQ_PREAUTH":                           "Kerberos 5, etype 23, AS-REQ Pre-Auth",
	"SAP_CODVN_B_BCODE":                                    "SAP CODVN B (BCODE)",
	"SAP_CODVN_B_BCODE_FROM_RFC_READ_TABLE":                "SAP CODVN B (BCODE) from RFC_READ_TABLE",
	"SAP_CODVN_F_G_PASSCODE":                               "SAP CODVN F/G (PASSCODE)",
	"SAP_CODVN_F_G_PASSCODE_FROM_RFC_READ_TABLE":           "SAP CODVN F/G (PASSCODE) from RFC_READ_TABLE",
	"DRUPAL7":                                              "Drupal7",
	"SYBASE_ASE":                                           "Sybase ASE",
	"CITRIX_NETSCALER_SHA1":                                "Citrix NetScaler (SHA1)",
	"HASHCAT_1PASSWORD_CLOUDKEYCHAIN":                      "1Password, cloudkeychain",
	"DNSSEC_NSEC3":                                         "DNSSEC (NSEC3)",
	"WBB3_WOLTLAB_BURNING_BOARD":                           "WBB3 (Woltlab Burning Board)",
	"RACF":                                                 "RACF",
	"AS_400_DES":                                           "AS/400 DES",
	"LOTUS_NOTES_DOMINO_5":                                 "Lotus Notes/Domino 5",
	"LOTUS_NOTES_DOMINO_6":                                 "Lotus Notes/Domino 6",
	"ANDROID_FDE_4_3":                                      "Android FDE <= 4.3",
	"SCRYPT":                                               "scrypt",
	"PASSWORD_SAFE_V2":                                     "Password Safe v2",
	"LOTUS_NOTES_DOMINO_8":                                 "Lotus Notes/Domino 8",
	"CISCO_IOS_PBKDF2_SHA256":                              "Cisco-IOS $8$ (PBKDF2-SHA256)",
	"CISCO_IOS_SCRYPT":                                     "Cisco-IOS $9$ (scrypt)",
	"MS_OFFICE_2007":                                       "MS Office 2007",
	"MS_OFFICE_2010":                                       "MS Office 2010",
	"MS_OFFICE_2013":                                       "MS Office 2013",
	"MS_OFFICE_2003_0_1_MD5_RC4":                           "MS Office <= 2003 $0/$1, MD5 + RC4",
	"MS_OFFICE_2003_0_1_MD5_RC4_COLLIDER_1":                "MS Office <= 2003 $0/$1, MD5 + RC4, collider #1",
	"MS_OFFICE_2003_0_1_MD5_RC4_COLLIDER_2":                "MS Office <= 2003 $0/$1, MD5 + RC4, collider #2",
	"MS_OFFICE_2003_3_4_SHA1_RC4":                          "MS Office <= 2003 $3/$4, SHA1 + RC4",
	"MS_OFFICE_2003_3_SHA1_RC4_COLLIDER_1":                 "MS Office <= 2003 $3, SHA1 + RC4, collider #1",
	"MS_OFFICE_2003_3_SHA1_RC4_COLLIDER_2":                 "MS Office <= 2003 $3, SHA1 + RC4, collider #2",
	"RADMIN2":                                              "Radmin2",
	"DJANGO_PBKDF2_SHA256":                                 "Django (PBKDF2-SHA256)",
	"SIPHASH":                                              "SipHash",
	"CRAM_MD5":                                             "CRAM-MD5",
	"SAP_CODVN_H_PWDSALTEDHASH_ISSHA_1":                    "SAP CODVN H (PWDSALTEDHASH) iSSHA-1",
	"PDF_1_1_1_3_ACROBAT_2_4":                              "PDF 1.1 - 1.3 (Acrobat 2 - 4)",
	"PDF_1_1_1_3_ACROBAT_2_4_COLLIDER_1":                   "PDF 1.1 - 1.3 (Acrobat 2 - 4), collider #1",
	"PDF_1_1_1_3_ACROBAT_2_4_COLLIDER_2":                   "PDF 1.1 - 1.3 (Acrobat 2 - 4), collider #2",
	"PDF_1_4_1_6_ACROBAT_5_8":                              "PDF 1.4 - 1.6 (Acrobat 5 - 8)",
	"PDF_1_3_1_6_ACROBAT_4_8_W_RC4_40":                     "PDF 1.3 - 1.6 (Acrobat 4 - 8) w/ RC4-40",
	"PDF_1_7_LEVEL_3_ACROBAT_9":                            "PDF 1.7 Level 3 (Acrobat 9)",
	"PDF_1_7_LEVEL_8_ACROBAT_10_11":                        "PDF 1.7 Level 8 (Acrobat 10 - 11)",
	"SHA2_384":                                             "SHA2-384",
	"SHA384_PASS_SALT":                                     "sha384($pass.$salt)",
	"SHA384_SALT_PASS":                                     "sha384($salt.$pass)",
	"SHA384_UTF16LE_PASS_SALT":                             "sha384(utf16le($pass).$salt)",
	"SHA384_SALT_UTF16LE_PASS":                             "sha384($salt.utf16le($pass))",
	"SHA384_UTF16LE":                                       "sha384(utf16le($pass))",
	"PBKDF2_HMAC_SHA256":                                   "PBKDF2-HMAC-SHA256",
	"REDHAT_389_DS_LDAP_PBKDF2_HMAC_SHA256":                "RedHat 389-DS LDAP (PBKDF2-HMAC-SHA256)",
	"PRESTASHOP":                                           "PrestaShop",
	"POSTGRESQL_CRAM_MD5":                                  "PostgreSQL CRAM (MD5)",
	"MYSQL_CRAM_SHA1":                                      "MySQL CRAM (SHA1)",
	"BITCOIN_LITECOIN_WALLET_DAT":                          "Bitcoin/Litecoin wallet.dat",
	"SIP_DIGEST":                                           "SIP digest authentication (MD5)",
	"CRC32":                                                "CRC32",
	"HASHCAT_7_ZIP":                                        "7-Zip",
	"GOST_R_32_11_2012_256":                                "GOST R 34.11-2012 (Streebog) 256-bit, big-endian",
	"HMAC_STREEBOG_256_KEY_PASS_BIG_ENDIAN":                "HMAC-Streebog-256 (key = $pass), big-endian",
	"HMAC_STREEBOG_256_KEY_SALT_BIG_ENDIAN":                "HMAC-Streebog-256 (key = $salt), big-endian",
	"GOST_R_32_11_2012_512":                                "GOST R 34.11-2012 (Streebog) 512-bit, big-endian",
	"HMAC_STREEBOG_512_KEY_PASS_BIG_ENDIAN":                "HMAC-Streebog-512 (key = $pass), big-endian",
	"HMAC_STREEBOG_512_KEY_SALT_BIG_ENDIAN":                "HMAC-Streebog-512 (key = $salt), big-endian",
	"PBKDF2_HMAC_MD5":                                      "PBKDF2-HMAC-MD5",
	"PBKDF2_HMAC_SHA1":                                     "PBKDF2-HMAC-SHA1",
	"ATLASSIAN_PBKDF2_HMAC_SHA1":                           "Atlassian (PBKDF2-HMAC-SHA1)",
	"PBKDF2_HMAC_SHA512":                                   "PBKDF2-HMAC-SHA512",
	"APACHE_SHIRO_1_SHA_512":                               "Apache Shiro 1 SHA-512",
	"ECRYPTFS":                                             "eCryptfs",
	"ORACLE_T_TYPE_ORACLE_12":                              "Oracle T: Type (Oracle 12+)",
	"BSDI_CRYPT":                                           "BSDi Crypt, Extended DES",
	"RAR3_HP":                                              "RAR3-hp",
	"COLDFUSION_10":                                        "ColdFusion 10+",
	"BLOCKCHAIN_MY_WALLET":                                 "Blockchain, My Wallet",
	"MS_AZURE_SYNC":                                        "MS-AzureSync PBKDF2-HMAC-SHA256",
	"ANDROID_FDE_SAMSUNG_DEK":                              "Android FDE (Samsung DEK)",
	"RAR5":                                                 "RAR5",
	"KERBEROS_23_TGS_REP":                                  "Kerberos 5, etype 23, TGS-REP",
	"AXCRYPT_1":                                            "AxCrypt 1",
	"AXCRYPT_1_IN_MEMORY_SHA1":                             "AxCrypt 1 in-memory SHA1",
	"KEEPASS_KDBX_V2_V3":                                   "KeePass (KDBX v2/v3)",
	"PEOPLESOFT_PS_TOKEN":                                  "PeopleSoft PS_TOKEN",
	"WINZIP":                                               "WinZip",
	"VERACRYPT_RIPEMD160_XTS_512_BIT_LEGACY":               "VeraCrypt RIPEMD160 + XTS 512 bit (legacy)",
	"VERACRYPT_RIPEMD160_XTS_1024_BIT_LEGACY":              "VeraCrypt RIPEMD160 + XTS 1024 bit (legacy)",
	"VERACRYPT_RIPEMD160_XTS_1536_BIT_LEGACY":              "VeraCrypt RIPEMD160 + XTS 1536 bit (legacy)",
	"VERACRYPT_SHA512_XTS_512_BIT_LEGACY":                  "VeraCrypt SHA512 + XTS 512 bit (legacy)",
	"VERACRYPT_SHA512_XTS_1024_BIT_LEGACY":                 "VeraCrypt SHA512 + XTS 1024 bit (legacy)",
	"VERACRYPT_SHA512_XTS_1536_BIT_LEGACY":                 "VeraCrypt SHA512 + XTS 1536 bit (legacy)",
	"VERACRYPT_WHIRLPOOL_XTS_512_BIT_LEGACY":               "VeraCrypt Whirlpool + XTS 512 bit (legacy)",
	"VERACRYPT_WHIRLPOOL_XTS_1024_BIT_LEGACY":              "VeraCrypt Whirlpool + XTS 1024 bit (legacy)",
	"VERACRYPT_WHIRLPOOL_XTS_1536_BIT_LEGACY":              "VeraCrypt Whirlpool + XTS 1536 bit (legacy)",
	"VERACRYPT_RIPEMD160_XTS_512_BIT_BOOT_MODE_LEGACY":     "VeraCrypt RIPEMD160 + XTS 512 bit + boot-mode (legacy)",
	"VERACRYPT_RIPEMD160_XTS_1024_BIT_BOOT_MODE_LEGACY":    "VeraCrypt RIPEMD160 + XTS 1024 bit + boot-mode (legacy)",
	"VERACRYPT_RIPEMD160_XTS_1536_BIT_BOOT_MODE_LEGACY":    "VeraCrypt RIPEMD160 + XTS 1536 bit + boot-mode (legacy)",
	"VERACRYPT_SHA256_XTS_512_BIT_LEGACY":                  "VeraCrypt SHA256 + XTS 512 bit (legacy)",
	"VERACRYPT_SHA256_XTS_1024_BIT_LEGACY":                 "VeraCrypt SHA256 + XTS 1024 bit (legacy)",
	"VERACRYPT_SHA256_XTS_1536_BIT_LEGACY":                 "VeraCrypt SHA256 + XTS 1536 bit (legacy)",
	"VERACRYPT_SHA256_XTS_512_BIT_BOOT_MODE_LEGACY":        "VeraCrypt SHA256 + XTS 512 bit + boot-mode (legacy)",
	"VERACRYPT_SHA256_XTS_1024_BIT_BOOT_MODE_LEGACY":       "VeraCrypt SHA256 + XTS 1024 bit + boot-mode (legacy)",
	"VERACRYPT_SHA256_XTS_1536_BIT_BOOT_MODE_LEGACY":       "VeraCrypt SHA256 + XTS 1536 bit + boot-mode (legacy)",
	"VERACRYPT_STREEBOG_512_XTS_512_BIT_LEGACY":            "VeraCrypt Streebog-512 + XTS 512 bit (legacy)",
	"VERACRYPT_STREEBOG_512_XTS_1024_BIT_LEGACY":           "VeraCrypt Streebog-512 + XTS 1024 bit (legacy)",
	"VERACRYPT_STREEBOG_512_XTS_1536_BIT_LEGACY":           "VeraCrypt Streebog-512 + XTS 1536 bit (legacy)",
	"VERACRYPT_STREEBOG_512_XTS_512_BIT_BOOT_MODE_LEGACY":  "VeraCrypt Streebog-512 + XTS 512 bit + boot-mode (legacy)",
	"VERACRYPT_STREEBOG_512_XTS_1024_BIT_BOOT_MODE_LEGACY": "VeraCrypt Streebog-512 + XTS 1024 bit + boot-mode (legacy)",
	"VERACRYPT_STREEBOG_512_XTS_1536_BIT_BOOT_MODE_LEGACY": "VeraCrypt Streebog-512 + XTS 1536 bit + boot-mode (legacy)",
	"WINDOWS_PHONE":                                        "Windows Phone 8+ PIN/password",
	"OPENCART":                                             "OpenCart",
	"DES":                                                  "DES (PT = $salt, key = $pass)",
	"THREE_DES":                                            "3DES (PT = $salt, key = $pass)",
	"RACF_KDFAES":                                          "RACF KDFAES",
	"SHA1_CX":                                              "sha1(CX)",
	"LINUX_KERNEL_CRYPTO_API_24":                           "Linux Kernel Crypto API (2.4)",
	"LUKS_V1_LEGACY":                                       "LUKS v1 (legacy)",
	"ITUNES_BACKUP_10_0_MODE_14700":                        "iTunes backup < 10.0",
	"ITUNES_BACKUP_10_0_MODE_14800":                        "iTunes backup >= 10.0",
	"SKIP_32":                                              "Skip32 (PT = $salt, key = $pass)",
	"FILEZILLA_SERVER_0_9_55":                              "FileZilla Server >= 0.9.55",
	"JUNIPER_NETBSD_SHA1CRYPT":                             "Juniper/NetBSD sha1crypt",
	"BLOCKCHAIN_MY_WALLET_V2":                              "Blockchain, My Wallet, V2",
	"DPAPI_V1_CTX_1_AND_2":                                 "DPAPI masterkey file v1 (context 1 and 2)",
	"DPAPI_V1_CTX_3":                                       "DPAPI masterkey file v1 (context 3)",
	"CHA_CHA_20":                                           "ChaCha20",
	"JKS_JAVA_KEY_STORE_PRIVATE_KEYS_SHA1":                 "JKS Java Key Store Private Keys (SHA1)",
	"ETHEREUM_WALLET_PBKDF2_HMAC_SHA256":                   "Ethereum Wallet, PBKDF2-HMAC-SHA256",
	"ETHEREUM_WALLET_SCRYPT":                               "Ethereum Wallet, SCRYPT",
	"DPAPI_V2_CTX_1_AND_2":                                 "DPAPI masterkey file v2 (context 1 and 2)",
	"DPAPI_V2_CTX_3":                                       "DPAPI masterkey file v2 (context 3)",
	"TRIPCODE":                                             "Tripcode",
	"TACACS_PLUS":                                          "TACACS+",
	"APPLE_SECURE_NOTES":                                   "Apple Secure Notes",
	"ETHEREUM_PRE_SALE_WALLET_PBKDF2_HMAC_SHA256":          "Ethereum Pre-Sale Wallet, PBKDF2-HMAC-SHA256",
	"CRAM_MD5_DOVECOT":                                     "CRAM-MD5 Dovecot",
	"JWT":                                                  "JWT (JSON Web Token)",
	"PERL_MOJOLICIOUS_SESSION_COOKIE_HMAC_SHA256_V9_19":    "Perl Mojolicious session cookie (HMAC-SHA256, >= v9.19)",
	"ELECTRUM_WALLET_SALT_TYPE_1_3":                        "Electrum Wallet (Salt-Type 1-3)",
	"FILEVAULT_2":                                          "FileVault 2",
	"WPA_PMKID_PBKDF2":                                     "WPA-PMKID-PBKDF2",
	"WPA_PMKID_PMK":                                        "WPA-PMKID-PMK",
	"ANSIBLE_VAULT":                                        "Ansible Vault",
	"GPG":                                                  "GPG (AES-128/AES-256 (SHA-1($pass)))",
	"GPG_AES_128_AES_256_SHA_512_PASS":                     "GPG (AES-128/AES-256 (SHA-512($pass)))",
	"GPG_AES_128_AES_256_SHA_256_PASS":                     "GPG (AES-128/AES-256 (SHA-256($pass)))",
	"GPG_CAST5_SHA_1_PASS":                                 "GPG (CAST5 (SHA-1($pass)))",
	"GPG_AES_OCB_128_SHA_1_PASS":                           "GPG (AES-OCB-128 (SHA-1($pass)))",
	"PKZIP_COMPRESSED":                                     "PKZIP (Compressed)",
	"PKZIP_UNCOMPRESSED":                                   "PKZIP (Uncompressed)",
	"PKZIP_COMPRESSED_MULTI_FILE":                          "PKZIP (Compressed Multi-File)",
	"PKZIP_MIXED_MULTI_FILE":                               "PKZIP (Mixed Multi-File)",
	"PKZIP_MIXED_MULTI_FILE_CHECKSUM_ONLY":                 "PKZIP (Mixed Multi-File Checksum-Only)",
	"SHA3_224":                                             "SHA3-224",
	"SHA3_256":                                             "SHA3-256",
	"SHA3_384":                                             "SHA3-384",
	"SHA3_512":                                             "SHA3-512",
	"KECCAK_224":                                           "Keccak-224",
	"KECCAK_256":                                           "Keccak-256",
	"KECCAK_384":                                           "Keccak-384",
	"KECCAK_512":                                           "Keccak-512",
	"TOTP_HMAC_SHA1":                                       "TOTP (HMAC-SHA1)",
	"KERBEROS_23_AS_REP":                                   "Kerberos 5, etype 23, AS-REP",
	"APPLE_FILE_SYSTEM_APFS":                               "Apple File System (APFS)",
	"OPEN_DOCUMENT_FORMAT_ODF_1_2_SHA_256_AES":             "Open Document Format (ODF) 1.2 (SHA-256, AES)",
	"SHA1_MD5_MD5_PASS":                                    "sha1(md5(md5($pass)))",
	"OPEN_DOCUMENT_FORMAT_ODF_1_1_SHA_1_BLOWFISH":          "Open Document Format (ODF) 1.1 (SHA-1, Blowfish)",
	"JAVA_OBJECT":                                          "Java Object hashCode()",
	"BLOCKCHAIN_MY_WALLET_SECOND_PASSWORD_SHA256":          "Blockchain, My Wallet, Second Password (SHA256)",
	"ANDROID_BACKUP":                                       "Android Backup",
	"QNX_MD5":                                              "QNX /etc/shadow (MD5)",
	"QNX_SHA256":                                           "QNX /etc/shadow (SHA256)",
	"QNX_SHA512":                                           "QNX /etc/shadow (SHA512)",
	"QNX_7_ETC_SHADOW_SHA512":                              "QNX 7 /etc/shadow (SHA512)",
	"SHA1_SALT1_PASS_SALT2":                                "sha1($salt1.$pass.$salt2)",
	"RUBY_ON_RAILS_RESTFUL_AUTHENTICATION":                 "Ruby on Rails Restful-Authentication",
	"KERBEROS_17_TGS_REP":                                  "Kerberos 5, etype 17, TGS-REP",
	"KERBEROS_18_TGS_REP":                                  "Kerberos 5, etype 18, TGS-REP",
	"KERBEROS_17_PREAUTH":                                  "Kerberos 5, etype 17, Pre-Auth",
	"KERBEROS_18_PREAUTH":                                  "Kerberos 5, etype 18, Pre-Auth",
	"DISKCRYPTOR_SHA512_XTS_512_BIT":                       "DiskCryptor SHA512 + XTS 512 bit",
	"DISKCRYPTOR_SHA512_XTS_1024_BIT":                      "DiskCryptor SHA512 + XTS 1024 bit",
	"DISKCRYPTOR_SHA512_XTS_1536_BIT":                      "DiskCryptor SHA512 + XTS 1536 bit",
	"PYTHON_PASSLIB_PBKDF2_SHA512":                         "Python passlib pbkdf2-sha512",
	"PYTHON_PASSLIB_PBKDF2_SHA256":                         "Python passlib pbkdf2-sha256",
	"PYTHON_PASSLIB_PBKDF2_SHA1":                           "Python passlib pbkdf2-sha1",
	"PKZIP_MASTER_KEY":                                     "PKZIP Master Key",
	"PKZIP_MASTER_KEY_6_BYTE_OPTIMIZATION":                 "PKZIP Master Key (6 byte optimization)",
	"ORACLE_TRANSPORTATION_MANAGEMENT_SHA256":              "Oracle Transportation Management (SHA256)",
	"SHA256_SHA256_PASS_SALT_MODE_20710":                   "sha256(sha256($pass).$salt)",
	"AUTHME_SHA256":                                        "AuthMe sha256",
	"RSA_SECURITY_ANALYTICS_NETWITNESS_SHA256":             "RSA Security Analytics / NetWitness (sha256)",
	"SHA256_SALT_SHA256_PASS":                              "sha256($salt.sha256($pass))",
	"SHA256_SHA256_PASS_SALT_MODE_20730":                   "sha256(sha256($pass.$salt))",
	"SHA256_MD5_PASS":                                      "sha256(md5($pass))",
	"MD5_SHA1_PASS_MD5_PASS_SHA1_PASS":                     "md5(sha1($pass).md5($pass).sha1($pass))",
	"BITSHARES_V0_X_SHA512_SHA512_BIN_PASS":                "BitShares v0.x - sha512(sha512_bin(pass))",
	"SHA1_MD5_PASS_SALT_MODE_21100":                        "sha1(md5($pass.$salt))",
	"MD5_SHA1_SALT_MD5_PASS":                               "md5(sha1($salt).md5($pass))",
	"MD5_SALT_SHA1_SALT_PASS":                              "md5($salt.sha1($salt.$pass))",
	"MD5_SALT1_SHA1_SALT2_PASS":                            "md5($salt1.sha1($salt2.$pass))",
	"SHA256_SHA256_BIN_PASS":                               "sha256(sha256_bin($pass))",
	"SHA256_SALT_SHA256_BIN_PASS":                          "sha256($salt.sha256_bin($pass))",
	"SOLARWINDS_ORION":                                     "SolarWinds Orion",
	"SOLARWINDS_ORION_V2":                                  "SolarWinds Orion v2",
	"WEB2PY_PBKDF2_SHA512":                                 "Web2py pbkdf2-sha512",
	"ELECTRUM_WALLET_SALT_TYPE_4":                          "Electrum Wallet (Salt-Type 4)",
	"ELECTRUM_WALLET_SALT_TYPE_5":                          "Electrum Wallet (Salt-Type 5)",
	"MD5_MD5_MD5_PASS_SALT1_SALT2_MODE_21900":              "md5(md5(md5($pass.$salt1)).$salt2)",
	"WPA_PBKDF2_PMKID_EAPOL":                               "WPA-PBKDF2-PMKID+EAPOL",
	"WPA_PMK_PMKID_EAPOL":                                  "WPA-PMK-PMKID+EAPOL",
	"BITLOCKER":                                            "BitLocker",
	"CITRIX_NETSCALER_SHA512":                              "Citrix NetScaler (SHA512)",
	"SHA256_SALT_PASS_SALT":                                "sha256($salt.$pass.$salt)",
	"TELEGRAM_MOBILE_APP_PASSCODE_SHA256":                  "Telegram Mobile App Passcode (SHA256)",
	"AES_CRYPT_SHA256":                                     "AES Crypt (SHA256)",
	"MULTIBIT_CLASSIC_KEY_MD5":                             "MultiBit Classic .key (MD5)",
	"TELEGRAM_DESKTOP_V2_1_14_PBKDF2_HMAC_SHA1":            "Telegram Desktop < v2.1.14 (PBKDF2-HMAC-SHA1)",
	"MULTIBIT_HD_SCRYPT":                                   "MultiBit HD (scrypt)",
	"SIMPLA_CMS_MD5_SALT_PASS_MD5_PASS":                    "Simpla CMS - md5($salt.$pass.md5($pass))",
	"RSA_DSA_EC_OPENSSH_PRIVATE_KEYS_0":                    "RSA/DSA/EC/OpenSSH Private Keys ($0$)",
	"RSA_DSA_EC_OPENSSH_PRIVATE_KEYS_6":                    "RSA/DSA/EC/OpenSSH Private Keys ($6$)",
	"RSA_DSA_EC_OPENSSH_PRIVATE_KEYS_1_3":                  "RSA/DSA/EC/OpenSSH Private Keys ($1, $3$)",
	"RSA_DSA_EC_OPENSSH_PRIVATE_KEYS_4":                    "RSA/DSA/EC/OpenSSH Private Keys ($4$)",
	"RSA_DSA_EC_OPENSSH_PRIVATE_KEYS_5":                    "RSA/DSA/EC/OpenSSH Private Keys ($5$)",
	"SECUREZIP_AES_128":                                    "SecureZIP AES-128",
	"SECUREZIP_AES_192":                                    "SecureZIP AES-192",
	"SECUREZIP_AES_256":                                    "SecureZIP AES-256",
	"APPLE_KEYCHAIN":                                       "Apple Keychain",
	"XMPP_SCRAM_PBKDF2_SHA1":                               "XMPP SCRAM PBKDF2-SHA1",
	"APPLE_IWORK":                                          "Apple iWork",
	"BITWARDEN":                                            "Bitwarden",
	"AXCRYPT_2_AES_128":                                    "AxCrypt 2 AES-128",
	"AXCRYPT_2_AES_256":                                    "AxCrypt 2 AES-256",
	"RAR3_P_UNCOMPRESSED":                                  "RAR3-p (Uncompressed)",
	"RAR3_P_COMPRESSED":                                    "RAR3-p (Compressed)",
	"BESTCRYPT_V3_VOLUME_ENCRYPTION":                       "BestCrypt v3 Volume Encryption",
	"BESTCRYPT_V4_VOLUME_ENCRYPTION":                       "BestCrypt v4 Volume Encryption",
	"MONGODB_SERVERKEY_SCRAM_SHA_1":                        "MongoDB ServerKey SCRAM-SHA-1",
	"MONGODB_SERVERKEY_SCRAM_SHA_256":                      "MongoDB ServerKey SCRAM-SHA-256",
	"SHA1_SALT_SHA1_PASS_SALT":                             "sha1($salt.sha1($pass.$salt))",
	"PKCS_8_PRIVATE_KEYS_PBKDF2_HMAC_SHA1_3DES_AES":        "PKCS#8 Private Keys (PBKDF2-HMAC-SHA1 + 3DES/AES)",
	"PKCS_8_PRIVATE_KEYS_PBKDF2_HMAC_SHA256_3DES_AES":      "PKCS#8 Private Keys (PBKDF2-HMAC-SHA256 + 3DES/AES)",
	"TELEGRAM_DESKTOP_V2_1_14_PBKDF2_HMAC_SHA512":          "Telegram Desktop >= v2.1.14 (PBKDF2-HMAC-SHA512)",
	"SQLCIPHER":                                            "SQLCipher",
	"STUFFIT5":                                             "Stuffit5",
	"UMBRACO_HMAC_SHA1":                                    "Umbraco HMAC-SHA1",
	"DAHUA_AUTHENTICATION_MD5":                             "Dahua Authentication MD5",
	"BESDER_AUTHENTICATION_MD5":                            "Besder Authentication MD5",
	"SNMP_V3_HMAC_MD5_96__SHA1_96":                         "SNMPv3 HMAC-MD5-96/HMAC-SHA1-96",
	"SNMP_V3_HMAC_MD5_96":                                  "SNMPv3 HMAC-MD5-96",
	"SNMP_V3_HMAC_SHA1_96":                                 "SNMPv3 HMAC-SHA1-96",
	"MS_OFFICE_2016_SHEETPROTECTION":                       "MS Office 2016 - SheetProtection",
	"PDF_1_4_1_6_ACROBAT_5_8_USER_AND_OWNER_PASS":          "PDF 1.4 - 1.6 (Acrobat 5 - 8) - user and owner pass",
	"STARGAZER_STELLAR_WALLET_XLM":                         "Stargazer Stellar Wallet XLM",
	"BCRYPT_MD5_PASS":                                      "bcrypt(md5($pass))",
	"MURMUR":                                               "MurmurHash",
	"BCRYPT_SHA1_PASS":                                     "bcrypt(sha1($pass))",
	"KNX_IP_SECURE_DEVICE_AUTHENTICATION_CODE":             "KNX IP Secure - Device Authentication Code",
	"MOZILLA_KEY3_DB":                                      "Mozilla key3.db",
	"MOZILLA_KEY4_DB":                                      "Mozilla key4.db",
	"OPENEDGE_PROGRESS_ENCODE":                             "OpenEdge Progress Encode",
	"FORTIGATE256_FORTIOS256":                              "FortiGate256 (FortiOS256)",
	"AES_128_ECB":                                          "AES-128-ECB NOKDF (PT = $salt, key = $pass)",
	"AES_192_ECB":                                          "AES-192-ECB NOKDF (PT = $salt, key = $pass)",
	"AES_256_ECB":                                          "AES-256-ECB NOKDF (PT = $salt, key = $pass)",
	"IPHONE_PASSCODE_UID_KEY_SYSTEM_KEYBAG":                "iPhone passcode (UID key + System Keybag)",
	"METAMASK_WALLET_NEEDS_ALL_DATA_CHECKS_AES_GCM_TAG":    "MetaMask Wallet (needs all data, checks AES-GCM tag)",
	"METAMASK_WALLET_SHORT_HASH_PLAINTEXT_CHECK":           "MetaMask Wallet (short hash, plaintext check)",
	"SNMP_V3_HMAC_SHA224_128":                              "SNMPv3 HMAC-SHA224-128",
	"SNMP_V3_HMAC_SHA256_192":                              "SNMPv3 HMAC-SHA256-192",
	"SNMP_V3_HMAC_SHA384_256":                              "SNMPv3 HMAC-SHA384-256",
	"NET_NTLM_V1_NT":                                       "NetNTLMv1 / NetNTLMv1+ESS (NT)",
	"NET_NTLM_V2_NT":                                       "NetNTLMv2 (NT)",
	"RUBY_ON_RAILS_RESTFUL_AUTH_ONE_ROUND_NO_SITEKEY":      "Ruby on Rails Restful Auth (one round, no sitekey)",
	"SNMP_V3_HMAC_SHA512_384":                              "SNMPv3 HMAC-SHA512-384",
	"VMWARE_VMX_PBKDF2_HMAC_SHA1_AES_256_CBC":              "VMware VMX (PBKDF2-HMAC-SHA1 + AES-256-CBC)",
	"VIRTUALBOX_PBKDF2_HMAC_SHA256_AES_128_XTS":            "VirtualBox (PBKDF2-HMAC-SHA256 & AES-128-XTS)",
	"VIRTUALBOX_PBKDF2_HMAC_SHA256_AES_256_XTS":            "VirtualBox (PBKDF2-HMAC-SHA256 & AES-256-XTS)",
	"MULTIBIT_CLASSIC_WALLET_SCRYPT":                       "MultiBit Classic .wallet (scrypt)",
	"MURMUR3":                                              "MurmurHash3",
	"CRC32C":                                               "CRC32C",
	"CRC64Jones":                                           "CRC64Jones",
	"WINDOWS_HELLO_PIN":                                    "Windows Hello PIN/Password",
	"EXODUS_DESKTOP_WALLET_SCRYPT":                         "Exodus Desktop Wallet (scrypt)",
	"TEAMSPEAK_3_CHANNEL_HASH":                             "Teamspeak 3 (channel hash)",
	"BCRYPT_SHA512_PASS":                                   "bcrypt(sha512($pass))",
	"BITCOIN_WIF_PRIVATE_KEY_P2PKH_COMPRESSED":             "Bitcoin WIF private key (P2PKH), compressed",
	"BITCOIN_WIF_PRIVATE_KEY_P2PKH_UNCOMPRESSED":           "Bitcoin WIF private key (P2PKH), uncompressed",
	"BITCOIN_WIF_PRIVATE_KEY_P2WPKH_BECH32_COMPRESSED":     "Bitcoin WIF private key (P2WPKH, Bech32), compressed",
	"BITCOIN_WIF_PRIVATE_KEY_P2WPKH_BECH32_UNCOMPRESSED":   "Bitcoin WIF private key (P2WPKH, Bech32), uncompressed",
	"BITCOIN_WIF_PRIVATE_KEY_P2SH_P2WPKH_COMPRESSED":       "Bitcoin WIF private key (P2SH(P2WPKH)), compressed",
	"BITCOIN_WIF_PRIVATE_KEY_P2SH_P2WPKH_UNCOMPRESSED":     "Bitcoin WIF private key (P2SH(P2WPKH)), uncompressed",
	"POSTGRESQL_SCRAM_SHA_256":                             "PostgreSQL SCRAM-SHA-256",
	"AMAZON_AWS_SIGNATURE_VERSION_4":                       "Amazon AWS Signature Version 4",
	"KERBEROS_17_DB":                                       "Kerberos 5, etype 17, DB",
	"KERBEROS_18_DB":                                       "Kerberos 5, etype 18, DB",
	"SHA1_SALT_SHA1_UTF16LE_USERNAME_UTF16LE_PASS":         "sha1($salt.sha1(utf16le($username).':'.utf16le($pass)))",
	"FLASK":                                                  "Flask Session Cookie ($salt.$salt.$pass)",
	"RADMIN_3":                                               "Radmin3",
	"TRUECRYPT_RIPEMD160_XTS_512_BIT":                        "TrueCrypt RIPEMD160 + XTS 512 bit",
	"TRUECRYPT_RIPEMD160_XTS_1024_BIT":                       "TrueCrypt RIPEMD160 + XTS 1024 bit",
	"TRUECRYPT_RIPEMD160_XTS_1536_BIT":                       "TrueCrypt RIPEMD160 + XTS 1536 bit",
	"TRUECRYPT_SHA512_XTS_512_BIT":                           "TrueCrypt SHA512 + XTS 512 bit",
	"TRUECRYPT_SHA512_XTS_1024_BIT":                          "TrueCrypt SHA512 + XTS 1024 bit",
	"TRUECRYPT_SHA512_XTS_1536_BIT":                          "TrueCrypt SHA512 + XTS 1536 bit",
	"TRUECRYPT_WHIRLPOOL_XTS_512_BIT":                        "TrueCrypt Whirlpool + XTS 512 bit",
	"TRUECRYPT_WHIRLPOOL_XTS_1024_BIT":                       "TrueCrypt Whirlpool + XTS 1024 bit",
	"TRUECRYPT_WHIRLPOOL_XTS_1536_BIT":                       "TrueCrypt Whirlpool + XTS 1536 bit",
	"TRUECRYPT_RIPEMD160_XTS_512_BIT_BOOT_MODE":              "TrueCrypt RIPEMD160 + XTS 512 bit + boot-mode",
	"TRUECRYPT_RIPEMD160_XTS_1024_BIT_BOOT_MODE":             "TrueCrypt RIPEMD160 + XTS 1024 bit + boot-mode",
	"TRUECRYPT_RIPEMD160_XTS_1536_BIT_BOOT_MODE":             "TrueCrypt RIPEMD160 + XTS 1536 bit + boot-mode",
	"VERACRYPT_RIPEMD160_XTS_512_BIT":                        "VeraCrypt RIPEMD160 + XTS 512 bit",
	"VERACRYPT_RIPEMD160_XTS_1024_BIT":                       "VeraCrypt RIPEMD160 + XTS 1024 bit",
	"VERACRYPT_RIPEMD160_XTS_1536_BIT":                       "VeraCrypt RIPEMD160 + XTS 1536 bit",
	"VERACRYPT_SHA512_XTS_512_BIT":                           "VeraCrypt SHA512 + XTS 512 bit",
	"VERACRYPT_SHA512_XTS_1024_BIT":                          "VeraCrypt SHA512 + XTS 1024 bit",
	"VERACRYPT_SHA512_XTS_1536_BIT":                          "VeraCrypt SHA512 + XTS 1536 bit",
	"VERACRYPT_WHIRLPOOL_XTS_512_BIT":                        "VeraCrypt Whirlpool + XTS 512 bit",
	"VERACRYPT_WHIRLPOOL_XTS_1024_BIT":                       "VeraCrypt Whirlpool + XTS 1024 bit",
	"VERACRYPT_WHIRLPOOL_XTS_1536_BIT":                       "VeraCrypt Whirlpool + XTS 1536 bit",
	"VERACRYPT_RIPEMD160_XTS_512_BIT_BOOT_MODE":              "VeraCrypt RIPEMD160 + XTS 512 bit + boot-mode",
	"VERACRYPT_RIPEMD160_XTS_1024_BIT_BOOT_MODE":             "VeraCrypt RIPEMD160 + XTS 1024 bit + boot-mode",
	"VERACRYPT_RIPEMD160_XTS_1536_BIT_BOOT_MODE":             "VeraCrypt RIPEMD160 + XTS 1536 bit + boot-mode",
	"VERACRYPT_SHA256_XTS_512_BIT":                           "VeraCrypt SHA256 + XTS 512 bit",
	"VERACRYPT_SHA256_XTS_1024_BIT":                          "VeraCrypt SHA256 + XTS 1024 bit",
	"VERACRYPT_SHA256_XTS_1536_BIT":                          "VeraCrypt SHA256 + XTS 1536 bit",
	"VERACRYPT_SHA256_XTS_512_BIT_BOOT_MODE":                 "VeraCrypt SHA256 + XTS 512 bit + boot-mode",
	"VERACRYPT_SHA256_XTS_1024_BIT_BOOT_MODE":                "VeraCrypt SHA256 + XTS 1024 bit + boot-mode",
	"VERACRYPT_SHA256_XTS_1536_BIT_BOOT_MODE":                "VeraCrypt SHA256 + XTS 1536 bit + boot-mode",
	"VERACRYPT_STREEBOG_512_XTS_512_BIT":                     "VeraCrypt Streebog-512 + XTS 512 bit",
	"VERACRYPT_STREEBOG_512_XTS_1024_BIT":                    "VeraCrypt Streebog-512 + XTS 1024 bit",
	"VERACRYPT_STREEBOG_512_XTS_1536_BIT":                    "VeraCrypt Streebog-512 + XTS 1536 bit",
	"VERACRYPT_STREEBOG_512_XTS_512_BIT_BOOT_MODE":           "VeraCrypt Streebog-512 + XTS 512 bit + boot-mode",
	"VERACRYPT_STREEBOG_512_XTS_1024_BIT_BOOT_MODE":          "VeraCrypt Streebog-512 + XTS 1024 bit + boot-mode",
	"VERACRYPT_STREEBOG_512_XTS_1536_BIT_BOOT_MODE":          "VeraCrypt Streebog-512 + XTS 1536 bit + boot-mode",
	"LUKS_V1_SHA_1_AES":                                      "LUKS v1 SHA-1 + AES",
	"LUKS_V1_SHA_1_SERPENT":                                  "LUKS v1 SHA-1 + Serpent",
	"LUKS_V1_SHA_1_TWOFISH":                                  "LUKS v1 SHA-1 + Twofish",
	"LUKS_V1_SHA_256_AES":                                    "LUKS v1 SHA-256 + AES",
	"LUKS_V1_SHA_256_SERPENT":                                "LUKS v1 SHA-256 + Serpent",
	"LUKS_V1_SHA_256_TWOFISH":                                "LUKS v1 SHA-256 + Twofish",
	"LUKS_V1_SHA_512_AES":                                    "LUKS v1 SHA-512 + AES",
	"LUKS_V1_SHA_512_SERPENT":                                "LUKS v1 SHA-512 + Serpent",
	"LUKS_V1_SHA_512_TWOFISH":                                "LUKS v1 SHA-512 + Twofish",
	"LUKS_V1_RIPEMD_160_AES":                                 "LUKS v1 RIPEMD-160 + AES",
	"LUKS_V1_RIPEMD_160_SERPENT":                             "LUKS v1 RIPEMD-160 + Serpent",
	"LUKS_V1_RIPEMD_160_TWOFISH":                             "LUKS v1 RIPEMD-160 + Twofish",
	"TERRA_STATION_WALLET_AES256_CBC_PBKDF2_PASS":            "Terra Station Wallet (AES256-CBC(PBKDF2($pass)))",
	"KEEPASS_KDBX_V2_V3_KEYFILE_ONLY":                        "KeePass (KDBX v2/v3) - keyfile only",
	"BISQ_WALLET_SCRYPT":                                     "Bisq .wallet (scrypt)",
	"ENCSECURITY_DATAVAULT_PBKDF2_NO_KEYCHAIN":               "ENCsecurity Datavault (PBKDF2/no keychain)",
	"ENCSECURITY_DATAVAULT_PBKDF2_KEYCHAIN":                  "ENCsecurity Datavault (PBKDF2/keychain)",
	"ENCSECURITY_DATAVAULT_MD5_NO_KEYCHAIN":                  "ENCsecurity Datavault (MD5/no keychain)",
	"ENCSECURITY_DATAVAULT_MD5_KEYCHAIN":                     "ENCsecurity Datavault (MD5/keychain)",
	"PYTHON_WERKZEUG_MD5_HMAC_MD5_KEY_SALT":                  "Python Werkzeug MD5 (HMAC-MD5 (key = $salt))",
	"PYTHON_WERKZEUG_SHA256_HMAC_SHA256_KEY_SALT":            "Python Werkzeug SHA256 (HMAC-SHA256 (key = $salt))",
	"DANE_RFC7929_RFC8162_SHA2_256":                          "DANE RFC7929/RFC8162 SHA2-256",
	"MD5_MD5_SALT_MD5_MD5_PASS":                              "md5(md5($salt).md5(md5($pass)))",
	"BCRYPT_SHA256_PASS":                                     "bcrypt(sha256($pass))",
	"BCRYPT_HMAC_SHA256_PASS":                                "bcrypt(HMAC-SHA256($pass))",
	"ANOPE_IRC_SERVICES_ENC_SHA256":                          "Anope IRC Services (enc_sha256)",
	"BITCOIN_RAW_PRIVATE_KEY_P2PKH_COMPRESSED":               "Bitcoin raw private key (P2PKH), compressed",
	"BITCOIN_RAW_PRIVATE_KEY_P2PKH_UNCOMPRESSED":             "Bitcoin raw private key (P2PKH), uncompressed",
	"BITCOIN_RAW_PRIVATE_KEY_P2WPKH_BECH32_COMPRESSED":       "Bitcoin raw private key (P2WPKH, Bech32), compressed",
	"BITCOIN_RAW_PRIVATE_KEY_P2WPKH_BECH32_UNCOMPRESSED":     "Bitcoin raw private key (P2WPKH, Bech32), uncompressed",
	"BITCOIN_RAW_PRIVATE_KEY_P2SH_P2WPKH_COMPRESSED":         "Bitcoin raw private key (P2SH(P2WPKH)), compressed",
	"BITCOIN_RAW_PRIVATE_KEY_P2SH_P2WPKH_UNCOMPRESSED":       "Bitcoin raw private key (P2SH(P2WPKH)), uncompressed",
	"BLAKE2S_256":                                            "BLAKE2s-256",
	"SHANGMI_3_SM3":                                          "ShangMi 3 (SM3)",
	"VEEAM_VBK":                                              "Veeam VBK",
	"MS_SNTP":                                                "MS SNTP",
	"SECURECRT_MASTERPASSPHRASE_V2":                          "SecureCRT MasterPassphrase v2",
	"DOMAIN_CACHED_CREDENTIALS_DCC_MS_CACHE_NT":              "Domain Cached Credentials (DCC), MS Cache (NT)",
	"DOMAIN_CACHED_CREDENTIALS_2_DCC2_MS_CACHE_2_NT":         "Domain Cached Credentials 2 (DCC2), MS Cache 2, (NT)",
	"MD5_MD5_MD5_PASS_SALT1_SALT2_MODE_31700":                "md5(md5(md5($pass).$salt1).$salt2)",
	"HASHCAT_1PASSWORD_MOBILEKEYCHAIN_1PASSWORD_8":           "1Password, mobilekeychain (1Password 8)",
	"METAMASK_MOBILE_WALLET":                                 "MetaMask Mobile Wallet",
	"NETIQ_SSPR_MD5":                                         "NetIQ SSPR (MD5)",
	"NETIQ_SSPR_SHA1":                                        "NetIQ SSPR (SHA1)",
	"NETIQ_SSPR_SHA_1_WITH_SALT":                             "NetIQ SSPR (SHA-1 with Salt)",
	"NETIQ_SSPR_SHA_256_WITH_SALT":                           "NetIQ SSPR (SHA-256 with Salt)",
	"ADOBE_AEM_SSPR_SHA_256_WITH_SALT":                       "Adobe AEM (SSPR, SHA-256 with Salt)",
	"NETIQ_SSPR_SHA_512_WITH_SALT":                           "NetIQ SSPR (SHA-512 with Salt)",
	"ADOBE_AEM_SSPR_SHA_512_WITH_SALT":                       "Adobe AEM (SSPR, SHA-512 with Salt)",
	"NETIQ_SSPR_PBKDF2WITHHMACSHA1":                          "NetIQ SSPR (PBKDF2WithHmacSHA1)",
	"NETIQ_SSPR_PBKDF2WITHHMACSHA256":                        "NetIQ SSPR (PBKDF2WithHmacSHA256)",
	"NETIQ_SSPR_PBKDF2WITHHMACSHA512":                        "NetIQ SSPR (PBKDF2WithHmacSHA512)",
	"KERBEROS_5_ETYPE_17_AS_REP":                             "Kerberos 5, etype 17, AS-REP",
	"KERBEROS_5_ETYPE_18_AS_REP":                             "Kerberos 5, etype 18, AS-REP",
	"EMPIRE_CMS_ADMIN_PASSWORD":                              "Empire CMS (Admin password)",
	"SHA512_SHA512_PASS_SALT":                                "sha512(sha512($pass).$salt)",
	"SHA512_SHA512_BIN_PASS_SALT":                            "sha512(sha512_bin($pass).$salt)",
	"DOGECHAIN_INFO_WALLET":                                  "Dogechain.info Wallet",
	"CUBECART_WHIRLPOOL_SALT_PASS_SALT":                      "CubeCart (whirlpool($salt.$pass.$salt))",
	"KREMLIN_ENCRYPT_3_0_W_NEWDES":                           "Kremlin Encrypt 3.0 w/NewDES",
	"MD5_SHA1_MD5_PASS":                                      "md5(sha1(md5($pass)))",
	"PBKDF1_SHA1":                                            "PBKDF1-SHA1",
	"MD5_SALT1_PASS_SALT2":                                   "md5($salt1.$pass.$salt2)",
	"MD5_SALT_MD5_PASS_SALT_MODE_33100":                      "md5($salt.md5($pass).$salt)",
	"HMAC_BLAKE2S_KEY_PASS":                                  "HMAC-BLAKE2S (key = $pass)",
	"MEGA_NZ_PASSWORD_PROTECTED_LINK_PBKDF2_HMAC_SHA512":     "mega.nz password-protected link (PBKDF2-HMAC-SHA512)",
	"RC4_40_BIT_DROPN":                                       "RC4 40-bit DropN",
	"RC4_72_BIT_DROPN":                                       "RC4 72-bit DropN",
	"RC4_104_BIT_DROPN":                                      "RC4 104-bit DropN",
	"RIPEMD_320":                                             "RIPEMD-320",
	"HMAC_RIPEMD320_KEY_PASS":                                "HMAC-RIPEMD320 (key = $pass)",
	"HMAC_RIPEMD320_KEY_SALT":                                "HMAC-RIPEMD320 (key = $salt)",
	"MICROSOFT_ONLINE_ACCOUNT_PBKDF2_HMAC_SHA256_AES256":     "Microsoft Online Account (PBKDF2-HMAC-SHA256 + AES256)",
	"WBB4_WOLTLAB_BURNING_BOARD_BCRYPT_BCRYPT_PASS":          "WBB4 (Woltlab Burning Board) [bcrypt(bcrypt($pass))]",
	"CITRIX_NETSCALER_PBKDF2_HMAC_SHA256":                    "Citrix NetScaler (PBKDF2-HMAC-SHA256)",
	"ARGON2":                                                 "Argon2",
	"LUKS_V2_ARGON2_SHA_256_AES":                             "LUKS v2 argon2 + SHA-256 + AES",
	"MURMURHASH64A":                                          "MurmurHash64A",
	"MURMURHASH64A_ZERO_SEED":                                "MurmurHash64A (zero seed)",
	"MURMURHASH64A_TRUNCATED_ZERO_SEED":                      "MurmurHash64A truncated (zero seed)",
	"KEEPASS_ARGON2_KDBX_V4":                                 "KeePass Argon2 (KDBX v4)",
	"KEEPASS_AESKDF_KDBX_V4":                                 "KeePass AESKDF (KDBX v4)",
	"SHA224_SHA224_PASS":                                     "sha224(sha224($pass))",
	"SHA224_SHA1_PASS":                                       "sha224(sha1($pass))",
	"MD6_256":                                                "MD6 (256)",
	"BLOCKCHAIN_MY_WALLET_LEGACY_WALLETS":                    "Blockchain, My Wallet, Legacy Wallets",
	"BLAKE2B_256_MODE_34800":                                 "BLAKE2b-256",
	"BLAKE2B_256_PASS_SALT":                                  "BLAKE2b-256($pass.$salt)",
	"BLAKE2B_256_SALT_PASS":                                  "BLAKE2b-256($salt.$pass)",
	"SAP_CODVN_H_PWDSALTEDHASH_ISSHA512":                     "SAP CODVN H (PWDSALTEDHASH) isSHA512",
	"SM3CRYPT_SM3_SM3_UNIX":                                  "sm3crypt $sm3$, SM3 (Unix)",
	"AS_400_SSHA1":                                           "AS/400 SSHA1",
	"KERBEROS_5_ETYPE_23_TGS_REP_NT":                         "Kerberos 5, etype 23, TGS-REP (NT)",
	"KERBEROS_5_ETYPE_23_AS_REP_NT":                          "Kerberos 5, etype 23, AS-REP (NT)",
	"WORDPRESS_BCRYPT_HMAC_SHA384_PASS":                      "Wordpress bcrypt(hmac-sha384($pass))",
	"GOST12512CRYPT_GOST12512HASH_UNIX":                      "gost12512crypt [$gost12512hash$] (Unix)",
	"PHPASS_MD5_PASS":                                        "phpass(md5($pass))",
	"SYMFONY_LEGACY_SHA256":                                  "Symfony Legacy SHA256",
	"YESCRYPT":                                               "yescrypt",
	"GOST_YESCRYPT":                                          "gost-yescrypt",
	"SCRYPTCRYPT_SCRYPT_UNIX":                                "scryptcrypt, scrypt (Unix)",
	"KDE_KWALLET_4_13_PBKDF2_HMAC_SHA512_BLOWFISH":           "KDE KWallet 4.13+ (PBKDF2-HMAC-SHA512, Blowfish)",
	"KDE_KWALLET_4_13_SHA_1_BLOWFISH":                        "KDE KWallet < 4.13 (SHA-1, Blowfish)",
	"ARGON2ID_BRIDGED_REFERENCE_IMPLEMENTATION_TUNINGS":      "Argon2id [Bridged: reference implementation + tunings]",
	"SCRYPT_BRIDGED_SCRYPT_JANE_SMIX":                        "scrypt [Bridged: Scrypt-Jane SMix]",
	"SCRYPT_BRIDGED_SCRYPT_YESCRYPT":                         "scrypt [Bridged: Scrypt-Yescrypt]",
	"GENERIC_HASH_BRIDGED_PYTHON_INTERPRETER_FREE_THREADING": "Generic Hash [Bridged: Python Interpreter free-threading]",
	"GENERIC_HASH_BRIDGED_PYTHON_INTERPRETER_WITH_GIL":       "Generic Hash [Bridged: Python Interpreter with GIL]",
	"GENERIC_HASH_BRIDGED_RUST":                              "Generic Hash [Bridged: Rust]",
	"PLAINTEXT":                                              "Plaintext",
}
