package crack

import "github.com/spf13/pflag"

func bindCrackFlags(f *pflag.FlagSet) {
	f.StringP("attack-mode", "a", "", "crack attack mode (straight, combination, bruteforce, pcfg, hybrid-wordlist-mask, hybrid-mask-wordlist, generic, association, no-attack, hybrid, or numeric)")
	f.StringP("hash-type", "m", "", "hashcat hash type (number or enum name)")
	f.Uint32("hash-mode", 0, "canonical numeric hashcat mode (overrides hash-type)")
	f.StringArray("hash", nil, "hashes to crack (repeatable)")
	f.StringArray("credential", nil, "server credential ID or ID prefix to crack (repeatable)")
	f.String("credential-collection", "", "server credential collection to crack")
	f.Bool("include-cracked-credentials", false, "include credentials already marked as cracked")
	f.StringArray("input", nil, "ordered positional hashcat inputs (repeatable)")
	f.String("stdin", "", "data supplied to hashcat standard input")
	f.Bool("quiet", false, "quiet mode")
	f.Bool("hex-charset", false, "treat charset as hex")
	f.Bool("hex-salt", false, "treat salt as hex")
	f.Bool("hex-wordlist", false, "treat wordlist as hex")
	f.Bool("force", false, "ignore warnings")
	f.Bool("deprecated-check-disable", false, "disable deprecated check")
	f.Bool("advice-disable", false, "disable hashcat advice")
	f.Bool("status", false, "enable status")
	f.Bool("status-json", false, "emit status in JSON")
	f.Uint32("status-timer", 0, "status timer interval (seconds)")
	f.Uint32("stdin-timeout-abort", 0, "abort after stdin timeout (seconds)")
	f.Bool("machine-readable", false, "machine readable output")
	f.Bool("keep-guessing", false, "keep guessing")
	f.Bool("self-test-disable", false, "disable self-test")
	f.Bool("loopback", false, "use loopback mode")
	f.String("markov-hcstat2", "", "markov hcstat2 filename or identifier")
	f.Bool("markov-disable", false, "disable markov mode")
	f.Bool("markov-classic", false, "use classic markov")
	f.Bool("markov-inverse", false, "use inverse markov")
	f.Uint32("markov-threshold", 0, "markov threshold")
	f.Uint32("runtime", 0, "runtime in seconds")
	f.String("session", "", "session name")
	f.Bool("restore", false, "restore session")
	f.Bool("restore-disable", false, "disable restore")
	f.String("restore-file", "", "restore file path or identifier")
	f.Bool("restore-position", false, "restore from the stored position")
	f.Bool("restore-show-command", false, "display the stored restore command and stop")
	f.String("outfile", "", "outfile path or identifier")
	f.StringSlice("outfile-format", nil, "outfile formats (hash-salt, plain, hex-plain, crack-pos, timestamp-absolute, timestamp-relative, or numeric)")
	f.Bool("outfile-json", false, "write outfile records as JSON")
	f.Bool("outfile-autohex-disable", false, "disable outfile autohex")
	f.Uint32("outfile-check-timer", 0, "outfile check timer interval (seconds)")
	f.Bool("wordlist-autohex-disable", false, "disable wordlist autohex")
	f.String("separator", "", "separator character")
	f.Bool("show", false, "show cracked hashes")
	f.Bool("left", false, "show uncracked hashes")
	f.Bool("username", false, "enable username handling")
	f.Bool("remove", false, "remove cracked hashes")
	f.Uint32("remove-timer", 0, "remove timer interval (seconds)")
	f.Bool("potfile-disable", false, "disable potfile")
	f.String("potfile", "", "potfile path or identifier")
	f.String("encoding-from", "", "input encoding name (legacy enum names and numbers are also accepted)")
	f.String("encoding-to", "", "output encoding name (legacy enum names and numbers are also accepted)")
	f.Uint32("debug-mode", 0, "debug mode mask")
	f.String("debug-file", "", "debug file path or identifier")
	f.String("induction-dir", "", "induction directory path or identifier")
	f.String("outfile-check-dir", "", "outfile-check directory path or identifier")
	f.Bool("logfile-disable", false, "disable logfile")
	f.Uint32("hccapx-message-pair", 0, "hccapx message pair")
	f.Uint32("nonce-error-corrections", 0, "nonce error corrections")
	f.String("keyboard-layout-mapping", "", "local keyboard layout mapping file")
	f.String("truecrypt-keyfiles", "", "TrueCrypt keyfiles path or identifier")
	f.String("veracrypt-keyfiles", "", "VeraCrypt keyfiles path or identifier")
	f.Uint32("veracrypt-pim-start", 0, "VeraCrypt PIM start")
	f.Uint32("veracrypt-pim-stop", 0, "VeraCrypt PIM stop")
	f.Bool("benchmark", false, "run benchmark")
	f.Bool("benchmark-all", false, "run full benchmark")
	f.Uint32("benchmark-min", 0, "minimum benchmark runtime")
	f.Uint32("benchmark-max", 0, "maximum benchmark runtime")
	f.Bool("speed-only", false, "show speed only")
	f.Bool("progress-only", false, "show progress only")
	f.Uint32("segment-size", 0, "deprecated: removed in Hashcat v7")
	f.Bool("pipeline-stats", false, "show pipeline statistics")
	f.Bool("task-time-breakdown", false, "show task time breakdown")
	f.Uint32("bitmap-min", 0, "bitmap min")
	f.Uint32("bitmap-max", 0, "bitmap max")
	f.UintSlice("cpu-affinity", nil, "CPU affinity list")
	f.Uint32("hook-threads", 0, "hook threads")
	f.Bool("hash-info", false, "show hash information from an idle crackstation (does not create a job)")
	f.Uint32("hash-info-level", 0, "hash information detail level: 1 or 2 (does not create a job)")
	f.Bool("backend-ignore-cuda", false, "ignore CUDA backend")
	f.Bool("backend-ignore-hip", false, "ignore HIP backend")
	f.Bool("backend-ignore-metal", false, "ignore Metal backend")
	f.Bool("backend-ignore-opencl", false, "ignore OpenCL backend")
	f.Bool("backend-info", false, "show registered backend info for all connected crackstations (does not create a job)")
	f.Uint32("backend-info-level", 0, "registered backend information detail level: 1 or 2 (does not create a job)")
	f.UintSlice("backend-devices", nil, "backend device IDs")
	f.Uint32("backend-devices-virtmulti", 0, "virtual backend device multiplier")
	f.Uint32("backend-devices-virthost", 0, "virtual backend host count")
	f.UintSlice("opencl-device-types", nil, "OpenCL device types")
	f.Uint32("metal-compiler-runtime", 0, "Metal compiler runtime")
	f.Bool("optimized-kernel-enable", false, "enable optimized kernels")
	f.Bool("multiply-accel-disable", false, "disable multiply accel")
	f.Bool("multiply-accel-disabled", false, "deprecated alias for multiply-accel-disable")
	_ = f.MarkDeprecated("multiply-accel-disabled", "use --multiply-accel-disable")
	_ = f.MarkHidden("multiply-accel-disabled")
	f.String("workload-profile", "", "deprecated: accepted but ignored by Hashcat v7")
	f.Uint32("kernel-accel", 0, "kernel acceleration")
	f.Uint32("kernel-loops", 0, "kernel loops")
	f.Uint32("kernel-threads", 0, "kernel threads")
	f.Uint32("backend-vector-width", 0, "backend vector width")
	f.Uint32("spin-damp", 0, "spin damp")
	f.Bool("hwmon-disable", false, "disable hardware monitoring")
	f.Uint32("hwmon-temp-abort", 0, "hardware monitor temperature abort")
	f.Uint32("scrypt-tmto", 0, "scrypt tmto")
	f.Uint64("skip", 0, "skip count")
	f.Uint64("limit", 0, "limit count")
	f.Bool("keyspace", false, "calculate keyspace on an idle crackstation and return it (does not create a job)")
	f.Bool("total-candidates", false, "calculate the total candidate count on an idle crackstation (does not create a job)")
	f.String("lookup", "", "locate a candidate in the attack on an idle crackstation (does not create a job)")
	f.String("crackstation", "", "target an exact crackstation name or host UUID for a synchronous query")
	f.Bool("dynamic-x", false, "enable dynamic-X mode")
	f.String("seekdb-path", "", "seek database path or identifier")
	f.String("rule-left", "", "left combinator rule")
	f.String("rule-right", "", "right combinator rule")
	f.StringArray("rules-file", nil, "rules file content or identifier (repeatable)")
	f.Uint32("generate-rules", 0, "generate rules")
	f.Uint32("generate-rules-func-min", 0, "generate rules function min")
	f.Uint32("generate-rules-func-max", 0, "generate rules function max")
	f.Uint32("generate-rules-fun-min", 0, "deprecated alias for generate-rules-func-min")
	f.Uint32("generate-rules-fun-max", 0, "deprecated alias for generate-rules-func-max")
	_ = f.MarkDeprecated("generate-rules-fun-min", "use --generate-rules-func-min")
	_ = f.MarkHidden("generate-rules-fun-min")
	_ = f.MarkDeprecated("generate-rules-fun-max", "use --generate-rules-func-max")
	_ = f.MarkHidden("generate-rules-fun-max")
	f.String("generate-rules-func-sel", "", "generate rules function selection")
	f.Int32("generate-rules-seed", 0, "generate rules seed")
	f.String("custom-charset1", "", "custom charset 1")
	f.String("custom-charset2", "", "custom charset 2")
	f.String("custom-charset3", "", "custom charset 3")
	f.String("custom-charset4", "", "custom charset 4")
	f.String("custom-charset5", "", "custom charset 5")
	f.String("custom-charset6", "", "custom charset 6")
	f.String("custom-charset7", "", "custom charset 7")
	f.String("custom-charset8", "", "custom charset 8")
	f.String("identify", "", "deprecated: legacy positional input")
	f.Bool("identify-mode", false, "identify hash types on an idle crackstation (does not create a job)")
	f.Bool("increment", false, "incremental mode")
	f.Bool("increment-inverse", false, "inverse incremental mode")
	f.Uint32("increment-min", 0, "increment min")
	f.Uint32("increment-max", 0, "increment max")
	f.Uint32("bypass-delay", 0, "bypass delay")
	f.Uint32("bypass-threshold", 0, "bypass threshold")
	f.Bool("slow-candidates", false, "slow candidates")
	f.String("bridge-parameter1", "", "bridge parameter 1")
	f.String("bridge-parameter2", "", "bridge parameter 2")
	f.String("bridge-parameter3", "", "bridge parameter 3")
	f.String("bridge-parameter4", "", "bridge parameter 4")
	f.Bool("brain-server", false, "brain server mode")
	f.Uint32("brain-server-timer", 0, "brain server timer")
	f.Bool("brain-client", false, "brain client mode")
	f.String("brain-client-features", "", "brain client features")
	f.String("brain-host", "", "brain host")
	f.Uint32("brain-port", 0, "brain port")
	f.String("brain-password", "", "brain password")
	f.String("brain-session", "", "brain session")
	f.String("brain-session-whitelist", "", "brain session whitelist")
	f.Bool("brain-feed", false, "brain feed mode")
	f.Bool("color-cracked", false, "color cracked output")
	f.Bool("hash-copy", false, "copy hashes")
	f.String("encrypt-with-pubkey", "", "public key path or identifier used to encrypt output")
}
